version: '3.7'
services:
    emailengine:
        restart: always
        image: andris9/emailengine
        ports:
            # API and web interface
            - '3000:3000'
            # Bull UI
            - '3001:3001'
            # SMTP for message submission
            - '2525:2525'
        depends_on:
            - redis
        environment:
            # Configuration to EmailEngine can be passed via environment variables
            # For full list see https://github.com/postalsys/emailengine#config-mapping

            # Settings to write to v1/settings on startup (https://api.emailengine.app/#operation/postV1Settings)
            # The following value is a YAML block scalar string, so make it sure it is properly indented
            EENGINE_SETTINGS: >
                {
                    "webhooks": "https://webhook.site/f6a00604-7407-4f40-9a8e-ab68a31a3503",
                    "webhookEvents": [
                        "messageNew", "messageDeleted"
                    ]
                }

            # Encryption secret
            EENGINE_SECRET: 'secret'
            # Database connection URL
            EENGINE_REDIS: 'redis://redis:6379/2'
            # Enable SMTP server for local submission
            EENGINE_SMTP_ENABLED: 'true'
            # Password for SMTP message submission clients (username is account ID)
            EENGINE_SMTP_SECRET: 'passw0rd'
            # Enable Bull UI server for debugging
            EENGINE_ARENA_ENABLED: 'true'

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - /data
