
[api]
port = 3000
host = "127.0.0.1" # by default API server is accessible from localhost only
maxSize = "5M" # maximum size of an attachment when submitting or uploading messages

[dbs]
# redis connection
redis = "redis://127.0.0.1:6379/8"

[log]
level = "trace"